In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import keras
import warnings
warnings.simplefilter('ignore')

In [2]:
df=pd.read_excel('D:\\self study\\Naresh IT\\Data Science\\21. ANN\\energy.xlsx')
df.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9568 entries, 0 to 9567
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   AT      9568 non-null   float64
 1   V       9568 non-null   float64
 2   AP      9568 non-null   float64
 3   RH      9568 non-null   float64
 4   PE      9568 non-null   float64
dtypes: float64(5)
memory usage: 373.9 KB


In [4]:
X= df.iloc[:,:-1].values
X

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [5]:
y= df.iloc[:,-1].values
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

# train test split

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=0,test_size=0.2)

In [7]:
X_train.shape

(7654, 4)

# modelling

In [8]:
from keras.models import Sequential

In [9]:
ann = Sequential()

## adding input layers and first hidden layers

In [10]:
from keras.layers import Dense

In [11]:
ann.add(Dense(input_dim= 4, units= 6, kernel_initializer= 'uniform',activation = 'relu'))

In [12]:
ann.add(Dense(units= 6,activation = 'relu'))

In [13]:
# adding second hidden layer

In [14]:
ann.add(Dense(units = 6, activation = 'relu'))

# adding output layer
ann.add(Dense(units = 1))


# compailing ANN

In [15]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

# training the Ann on training set

In [16]:
ann.fit(X_train,y_train,epochs =100,batch_size = 32)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 123048.6094
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 438.8243
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 411.4601
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 384.5864
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 352.7959
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 318.9488
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 284.2175
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 249.0301
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 213.9986
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 180.6882
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 149.9986
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - l

240/240 [==============================] - 0s 1ms/step - loss: 27.2583
Epoch 99/100
240/240 [==============================] - 0s 1ms/step - loss: 27.0634
Epoch 100/100
240/240 [==============================] - 0s 1ms/step - loss: 26.8407


In [17]:
y_train

array([473.93, 467.87, 431.97, ..., 459.01, 462.72, 428.12])

# prediction and evaluation

In [18]:
train_prediction = ann.predict(X_train)
test_prediction = ann.predict(X_test)

60/60 [==============================] - 0s 528us/step


In [19]:
train_prediction

array([[472.61835],
       [465.34155],
       [429.1474 ],
       ...,
       [465.62387],
       [472.5961 ],
       [429.24893]], dtype=float32)

In [20]:
test_prediction

array([[431.26715],
       [462.22678],
       [465.72406],
       ...,
       [472.95474],
       [439.73407],
       [458.9416 ]], dtype=float32)

In [21]:
from sklearn.metrics import r2_score
r2_score_train=r2_score(y_train,train_prediction)
r2_score_train


0.9116969948222688

In [22]:
r2_score_test=r2_score(y_test,test_prediction)
r2_score_test

0.9160668658485542

# cross validation 

In [23]:
def built_cross_classifier():
    classifier = Sequential()
    classifier.add(Dense(input_dim= 4,units=6,kernel_initializer= 'uniform', activation = 'relu'))
    classifier.add(Dense(units=6,kernel_initializer= 'uniform', activation = 'relu'))
    classifier.add(Dense(units=1,kernel_initializer= 'uniform', activation = 'relu'))
    classifier.compile(optimizer = 'rmsprop', loss = 'mean_squared_error')   
    return classifier

In [24]:
from keras.wrappers.scikit_learn import KerasRegressor

from scikeras.wrappers import KerasRegressor

In [25]:
classifier = KerasRegressor(built_cross_classifier, batch_size = 10,epochs = 50)

In [26]:
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

In [27]:
from sklearn.model_selection import cross_val_score
score= cross_val_score(classifier,X,y,cv = 5)
print(score)
score.mean()

Epoch 1/50
766/766 [==============================] - 1s 815us/step - loss: 206589.1094
Epoch 2/50
766/766 [==============================] - 1s 842us/step - loss: 206589.1094
Epoch 3/50
766/766 [==============================] - 1s 863us/step - loss: 206589.1562
Epoch 4/50
766/766 [==============================] - 1s 893us/step - loss: 206589.4062
Epoch 5/50
766/766 [==============================] - 1s 875us/step - loss: 206589.2031
Epoch 6/50
766/766 [==============================] - 1s 866us/step - loss: 206589.2031
Epoch 7/50
766/766 [==============================] - 1s 928us/step - loss: 206589.1719
Epoch 8/50
766/766 [==============================] - 1s 904us/step - loss: 206588.8750
Epoch 9/50
766/766 [==============================] - 1s 872us/step - loss: 206588.9531
Epoch 10/50
766/766 [==============================] - 1s 875us/step - loss: 206589.2344
Epoch 11/50
766/766 [==============================] - 1s 896us/step - loss: 206589.0938
Epoch 12/50
766/766 [=========

766/766 [==============================] - 1s 1ms/step - loss: 28.7501
Epoch 45/50
766/766 [==============================] - 1s 1ms/step - loss: 28.9838
Epoch 46/50
766/766 [==============================] - 1s 861us/step - loss: 29.0370
Epoch 47/50
766/766 [==============================] - 1s 1ms/step - loss: 29.0028
Epoch 48/50
766/766 [==============================] - 1s 1ms/step - loss: 29.3182
Epoch 49/50
766/766 [==============================] - 1s 1ms/step - loss: 28.9811
Epoch 50/50
192/192 [==============================] - 0s 654us/step
Epoch 1/50
766/766 [==============================] - 1s 846us/step - loss: 55157.6953
Epoch 2/50
766/766 [==============================] - 1s 875us/step - loss: 210.4251
Epoch 3/50
766/766 [==============================] - 1s 863us/step - loss: 92.5810
Epoch 4/50
766/766 [==============================] - 1s 850us/step - loss: 53.8895
Epoch 5/50
766/766 [==============================] - 1s 883us/step - loss: 41.1027
Epoch 6/50
766/766 

766/766 [==============================] - 1s 924us/step - loss: 206734.3281
Epoch 40/50
766/766 [==============================] - 1s 1ms/step - loss: 206734.2656
Epoch 41/50
766/766 [==============================] - 1s 1ms/step - loss: 206734.3281
Epoch 42/50
766/766 [==============================] - 1s 1ms/step - loss: 206734.2969
Epoch 43/50
766/766 [==============================] - 1s 925us/step - loss: 206734.4844
Epoch 44/50
766/766 [==============================] - 1s 1ms/step - loss: 206734.5000
Epoch 45/50
766/766 [==============================] - 1s 1ms/step - loss: 206734.3750
Epoch 46/50
766/766 [==============================] - 1s 981us/step - loss: 206734.2812
Epoch 47/50
766/766 [==============================] - 1s 924us/step - loss: 206734.3438
Epoch 48/50
766/766 [==============================] - 1s 927us/step - loss: 206734.2812
Epoch 49/50
766/766 [==============================] - 1s 924us/step - loss: 206734.3281
Epoch 50/50
192/192 [======================

-428.8727390671452